### ISSUE TITLE
example not working

### ISSUE THREAD

**Issue by niknoproblems** [epfl-lts2/pygsp#68]
I try to compute this example:
```
G = graphs.Torus()
G.compute_fourier_basis(n_eigenvectors=64)
G.U.shape
```
but got:

`TypeError: compute_fourier_basis() got an unexpected keyword argument 'n_eigenvectors'`

**Comment by mdeff** [comment]
That's because you are using the *stable* version of the PyGSP (installed by conda and pip) while you are looking at the *development* version of the documentation (corresponding to the github master branch). You can either install the development version with `pip install git+https://github.com/epfl-lts2/pygsp` or look at the stable documentation at <https://pygsp.readthedocs.io>.
