### ISSUE TITLE
`min_deg` argument  of Community class doesn't work?

### ISSUE THREAD

**Issue by mnagaa** [epfl-lts2/pygsp#86]
A question.

I want to choose the degree of Community graph.
I tried to specify the value, but the `min_deg` argument is not used in the __init__ function.

If someone knows about this, please tell me.

https://github.com/epfl-lts2/pygsp/blob/b7ca37c0f0eac7bb34167b6a7be0d2d5dbde7662/pygsp/graphs/community.py#L65

https://github.com/epfl-lts2/pygsp/blob/ff8c0023c25df4cbcfd88a7ef63c6223f3030a51/pygsp/graphs/community.py#L65

**Comment by nperraud** [comment]
It is not implemented. I guess we had some big plans at some point... We can add this option, but the question is what should be the expected behavior.
* Add random connections such that the minimum degree is satisfied?
* Add community connections such that the minimum degree is satisfied?

This would break the word and community density...

**Comment by Marusta** [comment]
Thanks for the answer ...
I understand that it's not implemented yet.
I was going to use it in my research, but it's going to be difficult in this case. (But pygsp has been very useful in my research. Thanks!)

If I had the time, I could collaborate with you, but I don't have the time right now, so I'll just suggest a simple method.

For example, if the minimum degree is set to 2, it may be possible to exclude independent nodes whose degree is less than 1. However, it would reduce the number of nodes in the community graph, so the problem is how to keep the initial number of nodes.

Or it may be possible to compensate for the degree by computing knn for the nodes with insufficient degree based on the pseudo-coordinates to reach the minimum degree.
