### ISSUE TITLE
maybe a bug about extract_components(self)

### ISSUE THREAD

**Issue by cuminx** [epfl-lts2/pygsp#93]
Hi,I try to use the extract_components(self) to get the connected components,but it always return the graph which I input. Then I read the source and find the code 'stack = set(np.nonzero(~visited)[0])' that build a stack with all nodes in graph, maybe it should be  'stack = set([np.nonzero(~visited)[0][0]])'? I think the stack should have only one node at the beginning, so that it can split the connected parts. Is that right?
<img width="391" alt="微信截图_20201225175209" src="https://user-images.githubusercontent.com/57053693/103131013-0378df00-46da-11eb-9f86-dee3d68b74bf.png">

**Comment by mdeff** [comment]
Thanks for reporting! That was fixed in #42. Unfortunately, the versions on pypi and conda don't contain the fix yet. You can install with `pip install git+https://github.com/epfl-lts2/pygsp`.

If you feel like contributing, it would be great to have a unit test for that function, so we don't break it in the future. :)
